"""MoE transformer at full scale: every seed shown, plus the LaTeX table.

Reads results/moe_transformer_fullscale.txt (one row per seed, copied from the Colab logs) and writes
  paper/figs/transformer_seeds.{pdf,png}   per-seed accuracy and illegal-transition rate
  paper/tab_transformer.tex                mean +- std table (\\input by paper/main.tex)
Add rows to the results file as more seeds finish, then re-run: python3 make_fig_transformer.py
"""
import os, statistics as st
import matplotlib.pyplot as plt
from figstyle import OURS, BASE, BASE2, NEUTRAL, INK2, MARK, save

HERE = os.path.dirname(os.path.abspath(__file__))
rows = []
for line in open(os.path.join(HERE, "results", "moe_transformer_fullscale.txt")):
    parts = [p.strip() for p in line.split("|")]
    if len(parts) == 8 and parts[0].isdigit():
        rows.append([int(parts[0])] + [float(p) for p in parts[1:]])
n = len(rows)
col = lambda i: [r[i] for r in rows]
dense, t1, t1i, t2, t2i, fl, fli = (col(i) for i in range(1, 8))

def ms(v):
    return f"${st.mean(v):.3f}\\pm{st.pstdev(v):.3f}$"

routers = [  # label, acc, illegal, active, color, marker
    ("dense (all 6)", dense, None, "6", NEUTRAL, MARK["neutral"]),
    ("top-1 gate", t1, t1i, "1", BASE, MARK["base"]),
    ("top-2 gate", t2, t2i, "2", BASE2, MARK["base2"]),
    ("conserved flow (ours)", fl, fli, "1$^\\dagger$", OURS, MARK["ours"]),
]

# ---------------- table
wins = sum(f > a for f, a in zip(fl, t1))
lines = [r"\begin{tabular}{lcccc}", r"\toprule",
         r"Router & token acc $\uparrow$ & median acc & experts/layer & illegal-transition $\downarrow$ \\",
         r"\midrule"]
for lab, acc, ill, act, _, _ in routers:
    name = lab.replace("top-1", "top-$1$").replace("top-2", "top-$2$").replace("(ours)", "(ours)")
    lines.append(f"{name} & {ms(acc)} & ${st.median(acc):.3f}$ & {act} & {ms(ill) if ill else '---'} \\\\")
lines += [r"\bottomrule", r"\end{tabular}"]
open(os.path.join(HERE, "paper", "tab_transformer.tex"), "w").write(
    f"% generated by make_fig_transformer.py from {n} seeds; flow beats top-1 on {wins}/{n} seeds\n"
    + "\n".join(lines) + "\n")
open(os.path.join(HERE, "paper", "transformer_stats.tex"), "w").write(
    f"\\newcommand{{\\tfN}}{{{n}}}\n\\newcommand{{\\tfWins}}{{{wins}}}\n"
    f"\\newcommand{{\\tfFlowIll}}{{{st.mean(fli):.3f}}}\n\\newcommand{{\\tfTopIll}}{{{st.mean(t1i):.3f}}}\n"
    f"\\newcommand{{\\tfFlowMax}}{{{max(fl):.3f}}}\n\\newcommand{{\\tfTopMean}}{{{st.mean(t1):.3f}}}\n"
    f"\\newcommand{{\\tfFlowMean}}{{{st.mean(fl):.3f}}}\n\\newcommand{{\\tfFlowMed}}{{{st.median(fl):.3f}}}\n")

# ---------------- figure: one dot per seed
fig, ax = plt.subplots(1, 2, figsize=(6.8, 2.3), gridspec_kw={"width_ratios": [1.25, 1]})
for k, (lab, acc, ill, _, c, m) in enumerate(routers):
    y = len(routers) - 1 - k
    jit = [(-0.18 + 0.36 * i / max(n - 1, 1)) for i in range(n)]
    ax[0].scatter(acc, [y + j for j in jit], color=c, marker=m, s=22, zorder=3, edgecolor="white", lw=0.5)
    ax[0].plot([st.median(acc)] * 2, [y - 0.3, y + 0.3], color=INK2, lw=1.2, zorder=2)
    if ill is not None:
        ax[1].scatter(ill, [y + j for j in jit], color=c, marker=m, s=22, zorder=3, edgecolor="white", lw=0.5)
        ax[1].plot([st.mean(ill)] * 2, [y - 0.3, y + 0.3], color=INK2, lw=1.2, zorder=2)
labels = [r[0] for r in routers][::-1]
for a in ax:
    a.set_yticks(range(len(routers))); a.set_ylim(-0.6, len(routers) - 0.4); a.grid(axis="y", visible=False)
ax[0].set_yticklabels(labels)
ax[1].set_yticklabels([])
ax[0].set_xlabel("token accuracy (bar = median)"); ax[0].set_xlim(0, 1.02)
ax[1].set_xlabel("illegal-transition rate (bar = mean)"); ax[1].set_xlim(-0.02, 0.62)
ax[0].set_title(f"(a) accuracy, {n} seeds", loc="left")
ax[1].set_title("(b) illegal expert transitions", loc="left")
save(fig, "transformer_seeds")
print(f"{n} seeds | flow wins {wins}/{n} | flow acc mean {st.mean(fl):.3f} median {st.median(fl):.3f} | "
      f"top1 {st.mean(t1):.3f} | flow ill {st.mean(fli):.3f} vs top1 {st.mean(t1i):.3f}")
